### ISSUE TITLE
The example is no longer running.

### ISSUE THREAD

**Issue by DuyTrandeLion** [watson-developer-cloud/raspberry-pi-speech-to-text#1]
Hello, 

I downloaded your code to my pi and and replaced the STT_USERNAME and STT_PASSWORD in the index.js file like the example. The npm install ran well but npm index.js fail to run. 
This is the error I received:
/home/pi/Downloads/raspberry-pi-speech-to-text-master/index.js:23
    username: process.env.a843566e-ef96-4a4f-8a99-7788bba29349,
                                        ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

Can you review the code? Thank you very much

**Comment by nfriedly** [comment]
You should replace the entire `process.env.STT_USERNAME` with the username (in quotes):

```js
var speech_to_text = watson.speech_to_text({
    username: "a843566e-ef96-4a4f-8a99-7788bba29349",
    password: "<password>",
    version: 'v1',
    url: 'https://stream.watsonplatform.net/speech-to-text/api'
});
```

**Comment by DuyTrandeLion** [comment]
Thank you for your reply nfriedly,
I replaced the entire process.env.STT_USERNAME and process.env.STT_PASSWORD, but I still have some errors like this:
fs.js:658
    return binding.writeBuffer(fd, buffer, offset, length, position);
                   ^

Error: EBUSY: resource busy or locked, write
    at Error (native)
    at Object.fs.writeSync (fs.js:658:20)
    at Object.fs.writeFileSync (fs.js:1165:24)
    at new Gpio (/home/pi/Downloads/raspberry-pi-speech-to-text-master/node_modules/onoff/onoff.js:84:8)
    at Object.<anonymous> (/home/pi/Downloads/raspberry-pi-speech-to-text-master/lightshow.js:3:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/Downloads/raspberry-pi-speech-to-text-master/index.js:3:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by nfriedly** [comment]
I think that means that your Pi is blocking you from using the GPIO pin (where the LED would be connected), possibly because something else is already using it.

You can try the solution at https://github.com/fivdi/onoff/issues/45 or just disable the LED by commenting out all of the the lines that reference `lightshow` in index.js

**Comment by DuyTrandeLion** [comment]
Thank you so much. I changed the pin and that error disappeared. Still there are some small errors ahead to fix 💃
